pipeline{
  agent {label 'DevServers' }
  stages{
    stage('build'){
      steps{
        sh 'maven clean package'
      }
      post{
        success{
          archiveArtifacts artifacts: '**/target/*.war'
        }
      }
    }

    // stage('test'){
    //   steps{
    //     echo "testing..."

    //   }
    // }
    
    // stage('deploy'){
    //   steps{
    //     echo "deploying..."
        
    //   }
    // }

  }
}